[package]
name = "particle_io"
version = "0.1.0"
edition = "2024"
rust-version = "1.91"

[dependencies]
bytemuck = { version = "1.24", features = ["derive"] }
postcard = "1.1.3"
rand = "0.9"
serde = "1.0.228"
vector2d = "3.1"
